---
version: "3"
services:
  repomanager:
    container_name: repomanager
    image: repomanager-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        fqdn: repomanager.example.com
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/docker/volumes/repomanager-data:/var/lib/repomanager
      - /var/lib/docker/volumes/repomanager-repo:/home/repo
